### ISSUE TITLE
archbuild: push extra package to chroot.

### ISSUE THREAD

**Issue by bartoszek** [archlinux/devtools#27]
Currently there's no way of using `makepkg.conf:buildenv=(ccache distcc)` in `archbuild`.
There should be a mechanism for inject extra packages to `base_packages` array to satisfy dependencies of external `makepkg` optimization features (like: ccache, distcc, upx, optipng etc.)

**Comment by anthraxx** [comment]
`ccache` should not really work because build containers are volatile, even if parts of the cache made persistent, input files are always being touched before a build which should defeat ccache effectiveness
`upx` and `optipng` are removed since quite a while (5.1)
`distcc` could be a thing, but then you also have a bit of hassle to nicely define remote hosts.plus i don't think it creates reproducible builds when using remote hosts

the best you could do right now is to use a specific `makepkg.conf` used explicitly in `makechrootpkg` allowing `distcc` (via makepkg-${repo}-${arch}.conf") and install requirements using `-- -I localpackage.pkg.tar.xz` into the container.
According to past experiences `distcc` output, when using remote hosts, is not binary reproducible. As this can't/shouldn't be used for official arch packages, i don't really have much motivation to even investigate potential implementations on this.

**Comment by bartoszek** [comment]
Nope, `ccache` works fine out of the box. Both makepkg and pacman preserves file creation/modification time, allowing `ccache` to resolve the file hash successfully. 

Can't really tell what could be the reproducibility problem with `distcc`. It's quite intriguing, will have to dive deeper into how's my build system working...

Yes, `upx/optipng..etc` are now provided by [`makepkg-optimize`](https://aur.archlinux.org/packages/makepkg-optimize). and in fact they works fine when inserted with `-- -I xxx` flag, thanks for the tip.

**Comment by anthraxx** [comment]
`makepkg-optimize` is nothing officially supported, you can't get it into the chroot (besides -I) if you don't use it as makedepends and when doing so you can also just add the appropriate optimization dependencies.

The modification time is not preserved when using the devtools in reproducible mode:
https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n1420
https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n84
https://github.com/archlinux/devtools/blob/master/archbuild.in#L86-L89

**Comment by bartoszek** [comment]
I haven't noticed there's a forced reproducibility enabled for core packages. Am I correct, there is no plan to forcing reproducibility for AUR packages?

**Comment by anthraxx** [comment]
With plain makepkg it's not forced to allow uses like incremental builds. With devtools it is enforced to provide reproducibility is all cases.
